#!/bin/sh

[ -z "$STOW_FOLDERS" ] || STOW_FOLDERS="debian,vim,zsh";

cd ~; zsh; rm .bashrc .zshrc; cd .dotfiles;

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
