- name: update and get
  hosts: localhost 
  become: true
  tasks:
    - name: Install packages with apt
      become: yes
      ansible.builtin.apt:
        name:
          - git
          - neofetch
          - fish
          - stow
          - fzf
          - vim
          - nodejs
          - curl
        state: present

    - name: clone dotfiles
      ansible.builtin.git:
        repo: https://github.com/lshevick/.dotfiles.git
        dest: "{{lookup('env', 'HOME')}}/.dotfiles"
        clone: true
        depth: 1

    - name: run stow 
      ansible.builtin.shell:
        chdir: "{{lookup('env', 'HOME')}}/.dotfiles"
        cmd: "stow ."

    - name: set up omf
      ansible.builtin.shell:
        chdir: "{{lookup('env', 'HOMNE')}}"
        cmd: "curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish"



