- name: update and get
  hosts: localhost 
  become: true
  tasks:
    - name: Install packages with apt
      become: yes
      ansible.builtin.apt:
        name:
          - git
          - neofetch
          - zsh 
          - stow
          - fzf
          - vim
          - nodejs
          - curl
        state: present

    - name: clone dotfiles
      ansible.builtin.git:
        repo: https://github.com/lshevick/.dotfiles.git
        dest: "{{lookup('env', 'HOME')}}/.dotfiles"
        clone: true
        depth: 1

    - name: rm default bashrc 
      ansible.builtin.shell:
        chdir: "{{lookup('env', 'HOME')}}"
        cmd: "rm .bashrc"
          
    - name: run stow 
      ansible.builtin.shell:
        chdir: "{{lookup('env', 'HOME')}}/.dotfiles"
        cmd: "stow ."



