- hosts: localhost 
  become: true 
  tasks:
    - name: Install zsh
      apt:
        pkg:
          - zsh
          - neofetch
          - fzf
          - vim
          - nodejs
          - stow

    - name: Change shell to zsh
      shell: chsh -s $(which zsh) 
        
    - name: Check zap install
      stat:
        path: /home/lshevick/.local/share/zap
      register: zap

    - name: Get zap if not installed
      shell: curl -L https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh > ~/.zapinstall && chmod +x ~/.zapinstall && ~/.zapinstall
      when: zap.stat.exists == false
      become_user: lshevick

    - name: Remove silly zap defaults
      shell: zsh && rm ~/.zshrc*
      become_user: lshevick
    
    - name: Stow .dotfiles
      shell: cd $HOME/.dotfiles && ./install
      become_user: lshevick

